# Generated by Django 5.1.1 on 2024-12-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy_mall', '0004_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='giver_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='message_to_receiver',
            field=models.TextField(blank=True, null=True),
        ),
    ]
