# Generated by Django 5.1.1 on 2024-09-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy_mall', '0005_rename_name_wishlist_title_remove_wishlist_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Filled'), ('filled', 'Filled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/products/'),
        ),
    ]
