# Generated by Django 5.1.1 on 2024-10-09 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy_mall', '0008_alter_cart_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synergy_mall.wishlist')),
                ('wishlist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synergy_mall.wishlistitem')),
            ],
        ),
    ]
